version: "3.9"

services:
  api:
    build: .
    container_name: pokeapi_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      RUNNING_IN_DOCKER: "true"
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/pokemondb
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
      - db

  redis:
    image: redis:7
    container_name: pokeapi_redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: pokeapi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokemondb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
