apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokeapi
  template:
    metadata:
      labels:
        app: pokeapi
    spec:
      containers:
        - name: api
          image: <your-image>
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: pokeapi-secrets
